version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:0.10.0.1-2
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=example:1:1
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  rig:
    image: accenture/reactive-interaction-gateway
    environment:
      - JWT_SECRET_KEY=mysecret
      - LOG_LEVEL=debug
      - KAFKA_SOURCE_TOPICS=example
      - KAFKA_BROKERS=kafka:9092
      - API_HTTP_PORT=7010
      - INBOUND_PORT=7000
      - JAEGER_HOST=jaeger
      - EXTRACTORS={"message":{"name":{"stable_field_index":1,"jwt":{"json_pointer":"/username"},"event":{"json_pointer":"/data/name"}}}}
    ports:
      - 7000:7000
      - 7010:7010
    depends_on:
      - kafka

  channels-external-service:
    image: channels-external-service
    environment:
      - KAFKA_HOSTS=kafka:9092
    ports:
      - 8000:8000

  channels-ui:
    image: channels-ui
    ports:
      - 3000:80
    depends_on:
      - rig
  
  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778 
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
