stages:
  - unittest
  - exampletest
  - name: dockerbuild
    if: branch = master
  - name: website
    if: branch = master AND type != pull_request
  - name: restore-helm-repo-index
    if: branch = master AND type != pull_request
  - name: sourcedocs
    if: branch = master AND type != pull_request

.elixir-env: &elixir-env
  language: elixir
  elixir: "1.10"
  otp_release: "22.0"

jobs:
  include:
    - stage: unittest
      <<: *elixir-env
      env:
        - MIX_ENV=test
      script:
        - mix test
        - mix credo --ignore-checks Design
    - stage: exampletest
      language: node_js
      node_js:
        - "10"
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      script:
        - cd examples/tests
        - npm ci
        - npm run cypress:run:all
    - stage: dockerbuild
      language: minimal
      services:
        - docker
      script:
        - docker build .
    - stage: website
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
    - stage: restore-helm-repo-index
      language: minimal
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - git fetch --unshallow
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch origin
        - git checkout gh-pages
        - test -e index.yaml || git checkout $(git rev-list -n1 HEAD -- index.yaml)~1 -- index.yaml
        - git add index.yaml
        - git diff-index --quiet HEAD || git commit -m "Auto-restore Helm chart repo index after Docusaurus publish"
        - git push
    - stage: sourcedocs
      <<: *elixir-env
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - GIT_USER="${GH_NAME}" mix publish_gh_pages
