stages:
  - unittest
  - exampletest
  - name: dockerbuild
    if: branch = master
  - name: website
    if: branch = master AND type != pull_request
  - name: sourcedocs
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: unittest
      language: elixir
      elixir: "1.7"
      otp_release: "21.0"
      env:
        - MIX_ENV=test
      script:
        - mix test
        - mix credo --ignore-checks Design
    - stage: exampletest
      language: node_js
      node_js:
        - "10"
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      script:
        - cd examples/tests
        - npm ci
        - npm run cypress:run:all
    - stage: dockerbuild
      language: minimal
      services:
        - docker
      script:
        - docker build .
    - stage: website
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
    - stage: sourcedocs
      language: elixir
      elixir: "1.7"
      otp_release: "21.0"
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - GIT_USER="${GH_NAME}" mix publish_gh_pages
