version: "2.1"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-dynamodb,kinesis,cloudwatch}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DEFAULT_REGION=eu-west-1

  rig:
    build:
      context: ../../
      dockerfile: aws.dockerfile
    container_name: reactive-interaction-gateway
    ports:
      - 4000:4000
      - 4010:4010
    environment:
      - LOG_LEVEL=debug
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - KINESIS_APP_NAME=rig
      - KINESIS_DYNAMODB_ENDPOINT=http://localstack:4566
      - KINESIS_ENABLED=1
      - KINESIS_ENDPOINT=http://localstack:4566
      - AWS_CBOR_DISABLE=1
      - JAEGER_HOST=jaeger
      # Using env var to set stream name is deprecated and will be removed in version 3.0!
      # - PROXY_KINESIS_REQUEST_STREAM=RIG-outbound

  jaeger:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
