version: "3"
services:
  localstack:
    image: localstack/localstack:0.12.2
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-dynamodb,kinesis,cloudwatch}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DEFAULT_REGION=eu-west-1

  zk:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zk
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure:5

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
    restart: on-failure:5

  kafkacat:
    image: confluentinc/cp-kafkacat:5.0.0
    container_name: kafkacat
    command: sh -c "sleep infinity"

  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: on-failure:5

  grafana:
    image: grafana/grafana:7.3.4
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./dashboards:/var/lib/grafana/dashboards/rig
    links:
      - prometheus
    restart: on-failure:5

  reactive-interaction-gateway:
    container_name: rig-metrics-container
    image: accenture/reactive-interaction-gateway
    environment:
      - LOG_LEVEL=debug
      # Kafka
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_SOURCE_TOPICS=test-monitoring
      # Kinesis
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - KINESIS_APP_NAME=rig
      - KINESIS_DYNAMODB_ENDPOINT=http://localstack:4566
      - KINESIS_ENABLED=1
      - KINESIS_ENDPOINT=http://localstack:4566
      - AWS_CBOR_DISABLE=1
      # Proxy
      - PROXY_CONFIG_FILE=/rig-proxy.json
      - KAFKA_HOST=kafka
    ports:
      - 4000:4000
      - 4010:4010
    volumes:
      - ./rig-proxy.json:/rig-proxy.json
    restart: on-failure:5
