apiVersion: v1
kind: Service
metadata:
  name: {{ template "reactive-interaction-gateway.name" . }}-headless
  labels:
    app: {{ template "reactive-interaction-gateway.name" . }}-headless
    chart: {{ template "reactive-interaction-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service_headless.type }}
  clusterIP: {{ .Values.service_headless.clusterIP }}
  ports:
    - port: {{ .Values.deployment.env.INBOUND_PORT }}
      targetPort: {{ .Values.deployment.env.INBOUND_PORT }}
      protocol: TCP
      name: proxy-http
    - port: {{ .Values.deployment.env.INBOUND_HTTPS_PORT }}
      targetPort: {{ .Values.deployment.env.INBOUND_HTTPS_PORT }}
      protocol: TCP
      name: proxy-https
    - port: {{ .Values.deployment.env.API_HTTP_PORT }}
      targetPort: {{ .Values.deployment.env.API_HTTP_PORT }}
      protocol: TCP
      name: internal-http
    - port: {{ .Values.deployment.env.API_HTTPS_PORT }}
      targetPort: {{ .Values.deployment.env.API_HTTPS_PORT }}
      protocol: TCP
      name: internal-https
  selector:
    app: {{ template "reactive-interaction-gateway.name" . }}
    release: {{ .Release.Name }}
